/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Pills by Poly by Google - 8XEcolZDyt5.glb --transform 
Files: Pills by Poly by Google - 8XEcolZDyt5.glb [3.65MB] > F:\My Documents\Sites\futuristic-caregiving\public\models\Pills by Poly by Google - 8XEcolZDyt5-transformed.glb [160.08KB] (96%)
*/

import React, { useMemo, useEffect } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'

export function ModelPillBottle({
  ...props
}) {
  const { nodes, materials } = useGLTF('models/Pill Bottle/Pill Bottle-transformed.glb')
  return (
    <group {...props} dispose={null}>

      <mesh geometry={nodes.Capsule090.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Capsule099.geometry} material={materials['03___Default']} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['02___Default']} />

      {/* <CustomLabel
        text={label}
        subText={subLabel}
        radius={labelRadius}
        height={labelHeight}
        position={labelPosition}
        rotation={labelRotation}
        {...labelProps}
      /> */}

    </group>
  )
}

useGLTF.preload('models/Pill Bottle/Pill Bottle-transformed.glb')

/**
 * CustomLabel wraps a dynamic text string along the side of a 3D cylinder.
 */
export function CustomLabel({
  text = 'CARE SPHERE PROTOCOL • 500MG • DAILY',
  subText = '',
  radius = 1.42,
  height = 2,
  radialSegments = 64,
  position = [0, 0, 0],
  rotation = [0, 0, 0],
  textColor = '#000000',
  backgroundColor = 'rgba(255, 255, 255, 0.95)',
  borderColor = '#ff0000',
  borderWidth = 8,
  fontSize = 100,
  fontFamily = 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  repeat = 1,
  canvasWidth = 2048,
  canvasHeight = 512,
  roughness = 0.3,
  metalness = 0.1,
  side = THREE.DoubleSide,
  ...meshProps
}) {
  // Generate dynamic canvas texture containing the wrapped string
  const texture = useMemo(() => {
    if (typeof document === 'undefined') return null

    const canvas = document.createElement('canvas')
    canvas.width = canvasWidth
    canvas.height = canvasHeight
    const ctx = canvas.getContext('2d')
    if (!ctx) return null

    // Background fill
    if (backgroundColor && backgroundColor !== 'transparent') {
      ctx.fillStyle = backgroundColor
      ctx.fillRect(0, 0, canvasWidth, canvasHeight)
    } else {
      ctx.clearRect(0, 0, canvasWidth, canvasHeight)
    }

    // Border outline
    if (borderWidth > 0 && borderColor) {
      ctx.strokeStyle = borderColor
      ctx.lineWidth = borderWidth
      ctx.strokeRect(
        borderWidth / 2,
        borderWidth / 2,
        canvasWidth - borderWidth,
        canvasHeight - borderWidth
      )
    }

    // Accent header line / decorative element
    ctx.strokeStyle = borderColor || '#00ffcc'
    ctx.lineWidth = 4
    ctx.beginPath()
    ctx.moveTo(canvasWidth * 0.05, canvasHeight * 0.15)
    ctx.lineTo(canvasWidth * 0.95, canvasHeight * 0.15)
    ctx.stroke()

    // Render repeated or formatted text
    const fullText = Array(repeat).fill(text).join('   •   ')

    ctx.textAlign = 'center'
    ctx.textBaseline = 'middle'

    if (subText) {
      // Primary / main string
      ctx.font = `700 ${fontSize}px ${fontFamily}`
      ctx.fillStyle = textColor
      ctx.letterSpacing = '2px'
      ctx.fillText(fullText, canvasWidth / 2, canvasHeight * 0.45)

      // Secondary / sub string
      ctx.font = `500 ${Math.round(fontSize * 0.42)}px ${fontFamily}`
      ctx.fillStyle = textColor
      ctx.globalAlpha = 0.75
      ctx.fillText(subText, canvasWidth / 2, canvasHeight * 0.75)
      ctx.globalAlpha = 1.0
    } else {
      ctx.font = `700 ${fontSize}px ${fontFamily}`
      ctx.fillStyle = textColor
      ctx.fillText(fullText, canvasWidth / 2, canvasHeight / 2)
    }

    const tex = new THREE.CanvasTexture(canvas)
    tex.wrapS = THREE.RepeatWrapping
    tex.wrapT = THREE.ClampToEdgeWrapping
    tex.colorSpace = THREE.SRGBColorSpace
    tex.needsUpdate = true
    return tex
  }, [
    text,
    subText,
    fontSize,
    fontFamily,
    textColor,
    backgroundColor,
    borderColor,
    borderWidth,
    repeat,
    canvasWidth,
    canvasHeight,
  ])

  // Clean up texture when unmounted or updated
  useEffect(() => {
    return () => {
      if (texture) texture.dispose()
    }
  }, [texture])

  return (
    <mesh position={position} rotation={rotation} {...meshProps}>
      {/* openEnded cylinder for clean label band */}
      <cylinderGeometry args={[radius, radius, height, radialSegments, 1, true]} />
      <meshStandardMaterial
        map={texture}
        transparent={true}
        side={side}
        roughness={roughness}
        metalness={metalness}
      />
    </mesh>
  )
}