/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Wheelchair.glb --transform 
Files: Wheelchair.glb [1.21MB] > F:\My Documents\Sites\futuristic-caregiving\public\models\Wheelchair\Wheelchair-transformed.glb [84.79KB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function ModelWheelchair({
  rotationSpeed = 0.6,
  bobHeight = 0.08,
  bobSpeed = 1.5,
  bobPhase = 0,
  ...props
}) {
  const { nodes, materials } = useGLTF('models/Wheelchair/Wheelchair-transformed.glb')
  const animationRef = useRef(null)

  useFrame((state, delta) => {
    if (!animationRef.current) return

    animationRef.current.rotation.y += rotationSpeed * delta
    animationRef.current.position.y =
      Math.sin(state.clock.elapsedTime * bobSpeed + bobPhase) * bobHeight
  })

  return (
    <group {...props} dispose={null}>
      <group ref={animationRef}>
        <mesh geometry={nodes.Node.geometry} material={materials.Cylinder} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Wheelchair/Wheelchair-transformed.glb')
