/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Hospital.glb --transform 
Files: Hospital.glb [726.8KB] > F:\My Documents\Sites\futuristic-caregiving\public\models\Hospital\Hospital-transformed.glb [109.06KB] (85%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelHospital(props) {
  const { nodes, materials } = useGLTF('models/Hospital/Hospital-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.Cube} />
    </group>
  )
}

useGLTF.preload('models/Hospital/Hospital-transformed.glb')
