/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Ambulance.glb --transform 
Files: Ambulance.glb [1.07MB] > F:\My Documents\Sites\futuristic-caregiving\public\models\Ambulance\Ambulance-transformed.glb [42.26KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelAmbulance(props) {
  const { nodes, materials } = useGLTF('models/Ambulance/Ambulance-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ambulance_mesh.geometry} material={materials.blinn1SG} />
    </group>
  )
}

useGLTF.preload('models/Ambulance/Ambulance-transformed.glb')
