/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Stethoscope.glb --transform 
Files: Stethoscope.glb [37.89KB] > F:\My Documents\Sites\futuristic-caregiving\public\models\Stethoscope\Stethoscope-transformed.glb [5.08KB] (87%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelStethoscope(props) {
  const { nodes, materials } = useGLTF('models/Stethoscope/Stethoscope-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.lambert2SG} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.lambert3SG} />
    </group>
  )
}

useGLTF.preload('models/Stethoscope/Stethoscope-transformed.glb')
